name: Go

on:
  push:
    branches: [ "main", "Realization" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache-dependency-path: go.sum
    - name: Installing dependencies
      run: sudo apt install sqlite3-tools
    
    - name: Setting timezone to Moscow # For tests with trips
      run: timedatectl set-timezone Europe/Moscow
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
